### 错误和异常的处理

错误和异常的处理主要通过**try/except**语句块来完成。try语句块包含**可能引发异常的代码**，而except语句块包含在**发生异常时应执行的代码**。



```python
try:
    x = 1 / 0
except ZeroDivisionError:
    x = 0
    print("除数为零，已处理此错误")
```

0不能作为分母，错误发生时程序不会崩溃，会跳到except语句块运行

##### 使用多个except块来处理不同类型的异常：

```python
try:
    # 尝试执行的代码
    x = 1 / 0
except ZeroDivisionError:
    # 处理除零异常
    print("除数为零")
except TypeError:
    # 处理类型错误异常
    print("类型错误")
except:
    # 处理所有其他类型的异常
    print("未知错误")
```

##### 使用finally块来确保无论是否发生异常都会执行某些操作：

```python
try:
    # 尝试执行的代码
    x = 1 / 0
except ZeroDivisionError:
    print("除数为零")
finally:
    print("这行输入要进行的操作")
```